spring.datasource.url=jdbc:postgresql://localhost:5432/seminovos
spring.datasource.username=
spring.datasource.password=
spring.datasource.drive-classs-name=org.postgresql.Drive

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true