spring.application.name=seminovos

api.security.token.secret=dGVzdGVzZWNyZXRrZXlmb3JqV1RoaXNpc2FzZWNyZXRrZXlmb3Jzc2VjdXJpdHk=
api.security.token.expiration= 68400000

app.admin.login=admin
app.admin.senha=admin123

spring.profiles.active=dev